// <auto-generated />
using System;
using Aegis.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Aegis.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603032111_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aegis.Api.Models.AlertaColisao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ALERTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DetritoEspacialId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("DetritoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DETRITO");

                    b.Property<int>("SateliteId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SATELITE");

                    b.Property<string>("StatusGravidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS_GRAVIDADE");

                    b.HasKey("Id");

                    b.HasIndex("DetritoEspacialId");

                    b.HasIndex("DetritoId");

                    b.HasIndex("SateliteId");

                    b.ToTable("TB_ALERTA_COLISAO", (string)null);
                });

            modelBuilder.Entity("Aegis.Api.Models.Chaser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CHASER");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Bateria")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("NUM_BATERIA");

                    b.Property<decimal>("CoordenadaX")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("TXT_COORDENADA_X");

                    b.Property<decimal>("CoordenadaY")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("TXT_COORDENADA_Y");

                    b.Property<decimal>("CoordenadaZ")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("TXT_COORDENADA_Z");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NOME_CHASER");

                    b.HasKey("Id");

                    b.ToTable("TB_CHASER", (string)null);
                });

            modelBuilder.Entity("Aegis.Api.Models.DetritoEspacial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DETRITO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CoordenadaX")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("TXT_COORDENADA_X");

                    b.Property<decimal>("CoordenadaY")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("TXT_COORDENADA_Y");

                    b.Property<decimal>("CoordenadaZ")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("TXT_COORDENADA_Z");

                    b.Property<decimal>("MassaKg")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("MASSA_KG");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME_DETRITO");

                    b.Property<decimal>("TamanhoMetros")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("TAMANHO_METROS");

                    b.HasKey("Id");

                    b.ToTable("TB_DETRITO_ESPACIAL", (string)null);
                });

            modelBuilder.Entity("Aegis.Api.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_EMPRESA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("CNPJ_ID_EMPRESA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME_EMPRESA");

                    b.Property<string>("PaisOrigem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("PAIS_ORIGEM");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS_OPERACAO");

                    b.HasKey("Id");

                    b.ToTable("TB_EMPRESA_AEROESPACIAL", (string)null);
                });

            modelBuilder.Entity("Aegis.Api.Models.MissaoInterceptacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MISSAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlertaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ALERTA");

                    b.Property<int>("ChaserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CHASER");

                    b.Property<int?>("ChaserId1")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DataExecucao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_EXECUCAO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS_MISSAO");

                    b.HasKey("Id");

                    b.HasIndex("AlertaId");

                    b.HasIndex("ChaserId");

                    b.HasIndex("ChaserId1");

                    b.ToTable("TB_MISSAO_INTERCEPTACAO", (string)null);
                });

            modelBuilder.Entity("Aegis.Api.Models.Satelite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SATELITE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AltitudeKm")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("NUMERO_ALTITUDE_KM");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_EMPRESA");

                    b.Property<string>("NumeroSatelite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NUMERO_SATELITE");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("TB_SATELITE", (string)null);
                });

            modelBuilder.Entity("Aegis.Api.Models.AlertaColisao", b =>
                {
                    b.HasOne("Aegis.Api.Models.DetritoEspacial", null)
                        .WithMany("Alertas")
                        .HasForeignKey("DetritoEspacialId");

                    b.HasOne("Aegis.Api.Models.DetritoEspacial", "Detrito")
                        .WithMany()
                        .HasForeignKey("DetritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aegis.Api.Models.Satelite", "Satelite")
                        .WithMany("Alertas")
                        .HasForeignKey("SateliteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detrito");

                    b.Navigation("Satelite");
                });

            modelBuilder.Entity("Aegis.Api.Models.MissaoInterceptacao", b =>
                {
                    b.HasOne("Aegis.Api.Models.AlertaColisao", "Alerta")
                        .WithMany()
                        .HasForeignKey("AlertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aegis.Api.Models.Chaser", "Chaser")
                        .WithMany()
                        .HasForeignKey("ChaserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aegis.Api.Models.Chaser", null)
                        .WithMany("Missoes")
                        .HasForeignKey("ChaserId1");

                    b.Navigation("Alerta");

                    b.Navigation("Chaser");
                });

            modelBuilder.Entity("Aegis.Api.Models.Satelite", b =>
                {
                    b.HasOne("Aegis.Api.Models.Empresa", "Empresa")
                        .WithMany("Satelites")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Aegis.Api.Models.Chaser", b =>
                {
                    b.Navigation("Missoes");
                });

            modelBuilder.Entity("Aegis.Api.Models.DetritoEspacial", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("Aegis.Api.Models.Empresa", b =>
                {
                    b.Navigation("Satelites");
                });

            modelBuilder.Entity("Aegis.Api.Models.Satelite", b =>
                {
                    b.Navigation("Alertas");
                });
#pragma warning restore 612, 618
        }
    }
}
