CREATE SEQUENCE SEQ_ALERTA_COLISAO START WITH 1;
CREATE SEQUENCE SEQ_DETRITO_ESPACIAL START WITH 1;
CREATE SEQUENCE SEQ_CHASER START WITH 1;
CREATE SEQUENCE SEQ_EMPRESA_AEROESPACIAL START WITH 1;
CREATE SEQUENCE SEQ_MISSAO_INTERCEPTACAO START WITH 1;
CREATE SEQUENCE SEQ_SATELITE START WITH 1;

-- 3. TABELAS (Nível 0 - Independentes)
CREATE TABLE TB_EMPRESA_AEROESPACIAL (
    id_empresa NUMBER NOT NULL PRIMARY KEY,
    nome_empresa VARCHAR2(100),
    cnpj_id_empresa VARCHAR2(20),
    pais_origem VARCHAR2(50),
    status_operacao VARCHAR2(20)
);

CREATE TABLE TB_CHASER (
    id_chaser NUMBER NOT NULL PRIMARY KEY,
    nome_chaser VARCHAR2(50),
    num_bateria NUMBER,
    status_chaser VARCHAR2(20),
    txt_coordenada_x NUMBER,
    txt_coordenada_y NUMBER,
    txt_coordenada_z NUMBER
);

CREATE TABLE TB_DETRITO_ESPACIAL (
    id_detrito NUMBER NOT NULL PRIMARY KEY,
    massa_kg NUMBER,
    tam_detrito_metros NUMBER,
    txt_coordenada_x NUMBER,
    txt_coordenada_y NUMBER,
    txt_coordenada_z NUMBER
);

-- 4. TABELAS (Nível 1 - Dependentes)
CREATE TABLE TB_SATELITE (
    id_satelite NUMBER NOT NULL PRIMARY KEY,
    id_empresa NUMBER NOT NULL,
    numero_satelite VARCHAR2(50),
    numero_altitude_km NUMBER,
    vel_satelite_kms NUMBER,
    txt_coordenada_x NUMBER,
    txt_coordenada_y NUMBER,
    txt_coordenada_z NUMBER,
    CONSTRAINT FK_SATELITE_EMPRESA FOREIGN KEY (id_empresa) REFERENCES TB_EMPRESA_AEROESPACIAL(id_empresa)
);

-- 5. TABELAS (Nível 2 - Relacionais)
-- Agora TB_ALERTA_COLISAO possui o relacionamento com DETRITO e SATELITE
CREATE TABLE TB_ALERTA_COLISAO (
    id_alerta NUMBER NOT NULL PRIMARY KEY,
    id_satelite NUMBER NOT NULL,
    id_detrito NUMBER NOT NULL,
    status_gravidade VARCHAR2(20),
    num_distancia_km NUMBER,
    CONSTRAINT FK_ALERTA_SATELITE FOREIGN KEY (id_satelite) REFERENCES TB_SATELITE(id_satelite),
    CONSTRAINT FK_ALERTA_DETRITO FOREIGN KEY (id_detrito) REFERENCES TB_DETRITO_ESPACIAL(id_detrito)
);

CREATE TABLE TB_MISSAO_INTERCEPTACAO (
    id_missao NUMBER NOT NULL PRIMARY KEY,
    id_alerta NUMBER NOT NULL,
    id_chaser NUMBER NOT NULL,
    data_inicio DATE,
    data_fim DATE,
    status_missao VARCHAR2(20),
    CONSTRAINT FK_MISSAO_ALERTA FOREIGN KEY (id_alerta) REFERENCES TB_ALERTA_COLISAO(id_alerta),
    CONSTRAINT FK_MISSAO_CHASER FOREIGN KEY (id_chaser) REFERENCES TB_CHASER(id_chaser)
);

-- 6. TRIGGERS
CREATE OR REPLACE TRIGGER TRG_EMPRESA_AEROESPACIAL
BEFORE INSERT ON TB_EMPRESA_AEROESPACIAL
FOR EACH ROW
BEGIN
    :NEW.ID_EMPRESA := SEQ_EMPRESA_AEROESPACIAL.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_CHASER
BEFORE INSERT ON TB_CHASER
FOR EACH ROW
BEGIN
    :NEW.ID_CHASER := SEQ_CHASER.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_DETRITO_ESPACIAL
BEFORE INSERT ON TB_DETRITO_ESPACIAL
FOR EACH ROW
BEGIN
    :NEW.ID_DETRITO := SEQ_DETRITO_ESPACIAL.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_SATELITE
BEFORE INSERT ON TB_SATELITE
FOR EACH ROW
BEGIN
    :NEW.ID_SATELITE := SEQ_SATELITE.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_ALERTA_COLISAO
BEFORE INSERT ON TB_ALERTA_COLISAO
FOR EACH ROW
BEGIN
    :NEW.ID_ALERTA := SEQ_ALERTA_COLISAO.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_MISSAO_INTERCEPTACAO
BEFORE INSERT ON TB_MISSAO_INTERCEPTACAO
FOR EACH ROW
BEGIN
    :NEW.ID_MISSAO := SEQ_MISSAO_INTERCEPTACAO.NEXTVAL;
END;
/